version: "3"

services:
  app:
    image: cms-ecommerce
    ports:
      - 3000:3000
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ecommerce-admin
      MYSQL_ROOT_PASSWORD: teddy123
